---
- name: restart squid
  systemd:
    daemon_reload: true
    name: squid
    state: restarted
  become: true
  tags: squid

- name: reload squid
  systemd:
    name: squid
    state: reloaded
  become: true
  tags: squid

- name: reload squidguard
  command: "/usr/lib/squidguard -b -d -C all -c {{ squid_config_dir }}/{{ squidguard_config_file }}"
  become: true
  tags: squidguard